version: '3.8'

services:
  frontend:
    build:
      context: ./saving-account-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./saving-account-backend
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/saving_account_db
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
